<a href="https://colab.research.google.com/github/MonishSoundarRaj/colab_files_1/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# scalar tensor
scalar = torch.tensor([7,3,4])
print(scalar)

tensor([7, 3, 4])


In [ ]:
scalar[2]

tensor(4)

In [ ]:
scalar.ndim

1

In [ ]:
#Tensor
tensor = torch.tensor([ [[4,8],[5,2],[5,5]],
                        [[2,2], [2,3], [4,4]],
                        [[3,3], [3,4],[5,6]]])
tensor

tensor([[[4, 8],
         [5, 2],
         [5, 5]],

        [[2, 2],
         [2, 3],
         [4, 4]],

        [[3, 3],
         [3, 4],
         [5, 6]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([3, 3, 2])

In [ ]:
# random Tensor -> why? random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust thise random numbers to better represent the sata.

random_tensor = torch.rand(2, 6, 3, 4)


In [ ]:
random_tensor

tensor([[[[0.7255, 0.2870, 0.4022, 0.8707],
          [0.9714, 0.4351, 0.4254, 0.0780],
          [0.5760, 0.3203, 0.5009, 0.4528]],

         [[0.5095, 0.2226, 0.9199, 0.3946],
          [0.0812, 0.8799, 0.1225, 0.9499],
          [0.2648, 0.9189, 0.1288, 0.3098]],

         [[0.4645, 0.4712, 0.6741, 0.1872],
          [0.2341, 0.4448, 0.7003, 0.1203],
          [0.1230, 0.8597, 0.7414, 0.5728]],

         [[0.4204, 0.9027, 0.9842, 0.3846],
          [0.3203, 0.1975, 0.4926, 0.7546],
          [0.9074, 0.9417, 0.8262, 0.1572]],

         [[0.0429, 0.0160, 0.5572, 0.8359],
          [0.8447, 0.7452, 0.8289, 0.7254],
          [0.9730, 0.3250, 0.8552, 0.5513]],

         [[0.8676, 0.4068, 0.9422, 0.6725],
          [0.9744, 0.7762, 0.6820, 0.7475],
          [0.5697, 0.7958, 0.1212, 0.0465]]],


        [[[0.0463, 0.1086, 0.1889, 0.3867],
          [0.7103, 0.5227, 0.1970, 0.3147],
          [0.3492, 0.5201, 0.1736, 0.9811]],

         [[0.4270, 0.7823, 0.8809, 0.8073],
          [0.118

In [ ]:
random_tensor.ndim

4

In [ ]:
random_image_size_tensor = torch.rand(224,224,3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.7697, 0.4174, 0.7956],
         [0.3870, 0.9194, 0.3903],
         [0.6133, 0.7190, 0.3191],
         ...,
         [0.3136, 0.5939, 0.2591],
         [0.0193, 0.1372, 0.8505],
         [0.0867, 0.3383, 0.3302]],

        [[0.0453, 0.9457, 0.6883],
         [0.9557, 0.6150, 0.2202],
         [0.8678, 0.7146, 0.5238],
         ...,
         [0.6844, 0.2456, 0.3697],
         [0.0627, 0.4845, 0.2259],
         [0.3063, 0.1074, 0.6235]],

        [[0.1293, 0.5179, 0.9573],
         [0.6143, 0.3418, 0.2298],
         [0.1319, 0.1187, 0.0035],
         ...,
         [0.6798, 0.4639, 0.5406],
         [0.0172, 0.2996, 0.8277],
         [0.5738, 0.7692, 0.6203]],

        ...,

        [[0.9165, 0.4280, 0.4345],
         [0.6005, 0.1015, 0.7179],
         [0.4401, 0.8171, 0.9154],
         ...,
         [0.0276, 0.8962, 0.2175],
         [0.1413, 0.0225, 0.0309],
         [0.0051, 0.9247, 0.9650]],

        [[0.1348, 0.0312, 0.4763],
         [0.7765, 0.5188, 0.8415],
         [0.

In [ ]:
# Tensors with zeros
zeros = torch.zeros(3,4)
ones = torch.ones(4,4)

In [ ]:
multi_tensor = torch.mm(zeros, ones)

In [ ]:
multi_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# dtype is nothing but data type

ones.dtype

torch.float32

In [ ]:
#  creating a range of tensors and tensors-lie
torch.range(1,10)

<ipython-input-72-75bf89bfffb4>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_thousand=torch.arange(0,1000,50)

In [ ]:
# creating tensors like
thousand_zeros = torch.zeros_like(input=one_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# device = "cuda, cpu" -> what deivec is tour tensor on
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # trackes


In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = float_16_tensor.type(torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
rand_tensor = torch.tensor([1,5,3])

In [ ]:
# addition
rand_tensor + 10

tensor([11, 15, 13])

In [ ]:
# mutliply tensor by 10
rand_tensor * 10

tensor([10, 50, 30])

In [ ]:
torch.mul(rand_tensor, 10)

tensor([10, 50, 30])

In [ ]:
torch.sub(rand_tensor, 10)

tensor([-9, -5, -7])

In [ ]:
rand_tensor*rand_tensor

tensor([ 1, 25,  9])

In [ ]:
torch.matmul(rand_tensor, rand_tensor)

tensor(35)

In [ ]:
rand_tensor_2 = torch.tensor([[1,2,3],
 [5,1,6]])


rand_tensor_2.shape

torch.Size([2, 3])

In [ ]:
rand_tensor_2.ndim

2

In [ ]:
%%time
value = 0
for i in range(len(rand_tensor)):
  value += rand_tensor[i] * rand_tensor[i]

value

CPU times: user 264 µs, sys: 0 ns, total: 264 µs
Wall time: 270 µs


tensor(35)

In [ ]:
%%time
torch.matmul(rand_tensor, rand_tensor)

CPU times: user 69 µs, sys: 4 µs, total: 73 µs
Wall time: 77.7 µs


tensor(35)

In [ ]:
 # Finding the min, max, mean, sum, etc (tensor aggregation)
 test_tensor = torch.tensor([[5,6,7],[8,2,1]])

 test_tensor.min()

tensor(1)

In [ ]:
test_tensor.max()

tensor(8)

In [ ]:
test_tensor.sum()

tensor(29)

In [ ]:
test_tensor.type(torch.float32).mean()

tensor(4.8333)

In [ ]:
test_tensor.argmax()

tensor(3)

In [ ]:
x = torch.arange(1, 10)


In [ ]:
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x.reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# View is going to share the same memory as the original one.


In [ ]:
x_stacked = torch.stack([x,x,x], dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_squeezed = x.squeeze()
x_squeezed

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_squeezed.unsqueeze(-2)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# squeeze removes all the single dimension of a tensor
# unsqueeze adds one sinlgle dimension to a tensor


In [ ]:
a_rand_tensor = torch.rand(5,6)

In [ ]:
a_rand_tensor

tensor([[0.1862, 0.7051, 0.3896, 0.1318, 0.9438, 0.3179],
        [0.2360, 0.0623, 0.2537, 0.1060, 0.0594, 0.6840],
        [0.8609, 0.1847, 0.3812, 0.1773, 0.2449, 0.6150],
        [0.5154, 0.0105, 0.5542, 0.9386, 0.4118, 0.7637],
        [0.1921, 0.8393, 0.6612, 0.7005, 0.2508, 0.4242]])

In [ ]:
a_rand_tensor[1][2]

tensor(0.2537)

In [ ]:
a_rand_tensor[1, :]

tensor([0.2360, 0.0623, 0.2537, 0.1060, 0.0594, 0.6840])

In [ ]:
# Random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
